const data = [
  {
    headline:
      "US Conducts Retaliatory Strikes on Iranian Forces; Crude Oil Prices Surge",
    summary:
      "The US military has conducted retaliatory strikes against Iranian boat forces, leading to an immediate increase in global crude oil prices by approximately $1. This geopolitical escalation in the Strait of Hormuz is expected to impact the Indian Rupee and market volatility.",
    category: "Geopolitics",
    impact_scope: "International",
    crime_severity: "NONE",
    emergency_type: "WAR_CONFLICT",
    importance_score: 8,
    sentiment: "Negative",
    tags: [
      "US-Iran Conflict",
      "Crude Oil",
      "Strait of Hormuz",
      "Geopolitical Tension",
    ],
    location: { state: null, district: null, is_national: false },
    entities: {
      people: [Array],
      organizations: [Array],
      monetary_values: [Array],
    },
    financials: null,
    source_context: {
      original_timestamp: "00:40",
      broadcast_date: "2024-05-21",
    },
  },
  {
    headline:
      "Finance Minister Signals Potential Review of LTCG and STCG Tax Structures",
    summary:
      "Finance Minister Nirmala Sitharaman has expressed openness to suggestions regarding the current Long-Term and Short-Term Capital Gains tax structures. This statement, made in Mumbai, has significantly boosted investor sentiment regarding FII returns and market stability.",
    category: "Politics",
    impact_scope: "National",
    crime_severity: "NONE",
    emergency_type: "NONE",
    importance_score: 9,
    sentiment: "Positive",
    tags: ["Nirmala Sitharaman", "LTCG", "STCG", "Tax Reform", "FII"],
    location: { state: "Maharashtra", district: "Mumbai", is_national: true },
    entities: { people: [Array], organizations: [Array], monetary_values: [] },
    financials: null,
    source_context: {
      original_timestamp: "02:15",
      broadcast_date: "2024-05-21",
    },
  },
  {
    headline: "IGL Hikes CNG Prices in NCR for the Fourth Time in 12 Days",
    summary:
      "Indraprastha Gas Limited (IGL) has announced a price hike of ₹2 per kg for CNG in the National Capital Region. This marks the fourth increase in less than two weeks, bringing the total hike to ₹6 per kg as the company passes on cost pressures.",
    category: "Economy",
    impact_scope: "District",
    crime_severity: "NONE",
    emergency_type: "NONE",
    importance_score: 6,
    sentiment: "Negative",
    tags: ["IGL", "CNG Price Hike", "NCR", "Inflation"],
    location: { state: "Delhi", district: "NCR", is_national: false },
    entities: { people: [], organizations: [Array], monetary_values: [Array] },
    financials: null,
    source_context: {
      original_timestamp: "10:50",
      broadcast_date: "2024-05-21",
    },
  },
  {
    headline:
      "Tata Sons Board to Discuss Air India Turnaround and Potential Listing",
    summary:
      "The Tata Sons board is scheduled to meet to review turnaround plans for Air India, Tata Digital, and Tata Electronics. The meeting is also expected to address the potential listing of Tata Sons, which has significant valuation implications for group companies like Tata Chemicals.",
    category: "Infrastructure",
    impact_scope: "National",
    crime_severity: "NONE",
    emergency_type: "NONE",
    importance_score: 7,
    sentiment: "Neutral",
    tags: ["Tata Sons", "Air India", "IPO", "N Chandrasekaran"],
    location: { state: null, district: null, is_national: true },
    entities: { people: [Array], organizations: [Array], monetary_values: [] },
    financials: null,
    source_context: {
      original_timestamp: "09:50",
      broadcast_date: "2024-05-21",
    },
  },
  {
    headline:
      "Raymond Board Approves ₹331 Crore Warrant Issuance to Promoters at Discount",
    summary:
      "Raymond's board has approved issuing 67 lakh warrants to JK Investors (promoters) at a price of ₹497 per share. This issue price is at an 11% discount to the current market price of ₹560, leading to a negative market reaction.",
    category: "Economy",
    impact_scope: "National",
    crime_severity: "NONE",
    emergency_type: "NONE",
    importance_score: 5,
    sentiment: "Negative",
    tags: ["Raymond", "Warrants", "Promoter Funding", "Corporate Action"],
    location: { state: "Maharashtra", district: "Mumbai", is_national: true },
    entities: { people: [], organizations: [Array], monetary_values: [Array] },
    financials: {
      type: "Budget Allocation",
      amount: 331,
      currency: "INR",
      denomination: "Crore",
      status: "Announced",
      industry: [Array],
    },
    source_context: {
      original_timestamp: "16:46",
      broadcast_date: "2024-05-21",
    },
  },
  {
    headline:
      "Premier Energies Sees Massive Institutional Buying via Bulk Deals",
    summary:
      "Despite promoters selling 2.4 crore shares, Premier Energies saw strong buying from marquee investors like Quant Mutual Fund, Nomura, and ADIA. The shares were sold at ₹955 but the stock maintained strength, closing higher at ₹985.",
    category: "Economy",
    impact_scope: "National",
    crime_severity: "NONE",
    emergency_type: "NONE",
    importance_score: 6,
    sentiment: "Positive",
    tags: [
      "Premier Energies",
      "Bulk Deal",
      "Institutional Investors",
      "Quant Mutual Fund",
    ],
    location: { state: null, district: null, is_national: true },
    entities: {
      people: [Array],
      organizations: [Array],
      monetary_values: [Array],
    },
    financials: {
      type: "null",
      amount: null,
      currency: "INR",
      denomination: "null",
      status: "Completed",
      industry: [Array],
    },
    source_context: {
      original_timestamp: "04:02",
      broadcast_date: "2024-05-21",
    },
  },
  {
    headline: "RVNL and CONCOR Report Weak Quarterly Earnings; Profits Decline",
    summary:
      "Public sector giants RVNL and CONCOR reported disappointing quarterly results. RVNL saw a 59% decline in profit despite a slight revenue increase, while CONCOR's profit fell by 12% due to execution hurdles and margin contraction.",
    category: "Infrastructure",
    impact_scope: "National",
    crime_severity: "NONE",
    emergency_type: "NONE",
    importance_score: 6,
    sentiment: "Negative",
    tags: ["RVNL", "CONCOR", "Earnings", "PSU"],
    location: { state: null, district: null, is_national: true },
    entities: { people: [], organizations: [Array], monetary_values: [] },
    financials: null,
    source_context: {
      original_timestamp: "16:04",
      broadcast_date: "2024-05-21",
    },
  },
  {
    headline: "Awfis Space Solutions Posts Record Profits with 108% Growth",
    summary:
      "Co-working space provider Awfis reported its best-ever quarterly performance, with net profit surging 108% to ₹108 crore. The company achieved record revenue and EBITDA margins of 37% during the period.",
    category: "Economy",
    impact_scope: "National",
    crime_severity: "NONE",
    emergency_type: "NONE",
    importance_score: 6,
    sentiment: "Positive",
    tags: ["Awfis", "Co-working", "Earnings", "Real Estate"],
    location: { state: null, district: null, is_national: true },
    entities: { people: [], organizations: [Array], monetary_values: [Array] },
    financials: {
      type: "null",
      amount: 108,
      currency: "INR",
      denomination: "Crore",
      status: "Completed",
      industry: [Array],
    },
    source_context: {
      original_timestamp: "08:44",
      broadcast_date: "2024-05-21",
    },
  },
  {
    headline: "CNBC Awaaz Hosts Inaugural Bharat Economic Summit in New Delhi",
    summary:
      "CNBC Awaaz has launched the first edition of the Bharat Economic Summit at the Taj Palace in New Delhi. The summit aims to address global economic challenges and discuss India's growth trajectory with top policymakers.",
    category: "Politics",
    impact_scope: "National",
    crime_severity: "NONE",
    emergency_type: "NONE",
    importance_score: 7,
    sentiment: "Positive",
    tags: [
      "Bharat Economic Summit",
      "CNBC Awaaz",
      "Economic Policy",
      "New Delhi",
    ],
    location: { state: "Delhi", district: "New Delhi", is_national: true },
    entities: { people: [], organizations: [Array], monetary_values: [] },
    financials: null,
    source_context: {
      original_timestamp: "23:15",
      broadcast_date: "2024-05-21",
    },
  },
  {
    headline: "BEL Receives Cumulative Orders Worth ₹68 Crore",
    summary:
      "Bharat Electronics Limited (BEL) has updated the market regarding new cumulative orders worth ₹68 crore. The stock remains a focus for investors due to its strong technical chart structure and consistent order pipeline.",
    category: "Infrastructure",
    impact_scope: "National",
    crime_severity: "NONE",
    emergency_type: "NONE",
    importance_score: 5,
    sentiment: "Positive",
    tags: ["BEL", "Defense Orders", "PSU", "Manufacturing"],
    location: { state: "Karnataka", district: "Bengaluru", is_national: true },
    entities: { people: [], organizations: [Array], monetary_values: [Array] },
    financials: {
      type: "null",
      amount: 68,
      currency: "INR",
      denomination: "Crore",
      status: "Signed",
      industry: [Array],
    },
    source_context: {
      original_timestamp: "17:40",
      broadcast_date: "2024-05-21",
    },
  },
];
